// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8IyPxYjud20pIknQI0rkrwDAMqNW4aJs',
    appId: '1:462327085158:web:1e66635454d4f7ec0f95a7',
    messagingSenderId: '462327085158',
    projectId: 'finndata-1c7e0',
    authDomain: 'finndata-1c7e0.firebaseapp.com',
    storageBucket: 'finndata-1c7e0.appspot.com',
    measurementId: 'G-R33Q50SGV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3qLHaqwMzGvmNAbDriIlrUceuHN6wtF8',
    appId: '1:462327085158:android:7a9e5508a575ab840f95a7',
    messagingSenderId: '462327085158',
    projectId: 'finndata-1c7e0',
    storageBucket: 'finndata-1c7e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk0oq5kTu4XbC37rtPSvRa8GQ6esMDI-4',
    appId: '1:462327085158:ios:783cee612299e6a40f95a7',
    messagingSenderId: '462327085158',
    projectId: 'finndata-1c7e0',
    storageBucket: 'finndata-1c7e0.appspot.com',
    iosClientId: '462327085158-gnrj5aruv5nl29d60s16n0hlbm82f2j6.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
